-- Hora em UTC como texto 'AAAA-MM-DD HH:MM:SS' (formato que o sistema sempre usou), com deslocamento opcional: agora('+7 days').
CREATE FUNCTION agora(deslocamento TEXT DEFAULT NULL) RETURNS TEXT LANGUAGE sql STABLE AS $$
  SELECT to_char((now() AT TIME ZONE 'utc') + COALESCE(deslocamento, '0')::interval, 'YYYY-MM-DD HH24:MI:SS')
$$;

-- Usuário e membro são a mesma entidade: quem tem e-mail e senha entra no painel.
CREATE TABLE usuarios (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome TEXT NOT NULL,
  telefone TEXT,                       -- somente dígitos (DDD + número)
  data_nascimento TEXT,                -- AAAA-MM-DD
  email TEXT,
  foto TEXT,
  funcao TEXT NOT NULL DEFAULT 'membro' CHECK (funcao IN ('coordenacao', 'membro')),
  senha_hash TEXT,
  ativo INTEGER NOT NULL DEFAULT 1 CHECK (ativo IN (0, 1)),
  consentimento_lgpd_em TEXT,
  criado_em TEXT NOT NULL DEFAULT agora(),
  atualizado_em TEXT NOT NULL DEFAULT agora()
);
CREATE UNIQUE INDEX uq_usuarios_email ON usuarios (LOWER(email));
CREATE INDEX idx_usuarios_nome ON usuarios (LOWER(nome));
CREATE INDEX idx_usuarios_ativo ON usuarios (ativo);

-- @down
DROP TABLE usuarios;
DROP FUNCTION agora(TEXT);
