CREATE TABLE auditoria (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id INTEGER REFERENCES usuarios (id),
  acao TEXT NOT NULL,
  entidade TEXT NOT NULL,
  entidade_id INTEGER,
  detalhes TEXT,
  criado_em TEXT NOT NULL DEFAULT agora()
);
CREATE INDEX idx_auditoria_entidade ON auditoria (entidade, entidade_id);

-- @down
DROP TABLE auditoria;
