-- Galeria: eventos com fotos. Quem tem a guia vê e baixa; só Coordenação/Administrador edita.
CREATE TABLE eventos (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titulo TEXT NOT NULL,
  descricao TEXT,
  data_evento TEXT NOT NULL,           -- AAAA-MM-DD
  capa_foto_id INTEGER,                -- foto escolhida como capa (senão, a primeira)
  criado_por INTEGER REFERENCES usuarios (id),
  criado_em TEXT NOT NULL DEFAULT agora(),
  atualizado_em TEXT NOT NULL DEFAULT agora()
);
CREATE INDEX idx_eventos_data ON eventos (data_evento);

CREATE TABLE fotos (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  evento_id INTEGER NOT NULL REFERENCES eventos (id) ON DELETE CASCADE,
  arquivo TEXT NOT NULL,
  titulo TEXT,
  criado_por INTEGER REFERENCES usuarios (id),
  criado_em TEXT NOT NULL DEFAULT agora()
);
CREATE INDEX idx_fotos_evento ON fotos (evento_id);

-- A lista de guias permitidas em usuario_guias passa a ser validada pela aplicação (mudava a cada guia nova).
ALTER TABLE usuario_guias DROP CONSTRAINT usuario_guias_guia_check;

-- @down
DELETE FROM usuario_guias WHERE guia NOT IN ('minha-presenca', 'frequencia', 'aniversariantes', 'avisos', 'membros', 'financeiro');
ALTER TABLE usuario_guias ADD CONSTRAINT usuario_guias_guia_check
  CHECK (guia IN ('minha-presenca', 'frequencia', 'aniversariantes', 'avisos', 'membros', 'financeiro'));
DROP TABLE fotos;
DROP TABLE eventos;
