-- Notificações do sino: geradas quando sai aviso novo, evento novo ou fotos novas na galeria.
-- A notificação é única; a leitura é por pessoa. Quem não tem a guia do assunto não a vê.
CREATE TABLE notificacoes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo TEXT NOT NULL CHECK (tipo IN ('aviso', 'evento', 'fotos')),
  referencia_id INTEGER NOT NULL,      -- id do aviso ou do evento
  titulo TEXT NOT NULL,
  mensagem TEXT,
  link TEXT NOT NULL,
  criado_por INTEGER REFERENCES usuarios (id),
  criado_em TEXT NOT NULL DEFAULT agora()
);
CREATE INDEX idx_notificacoes_ref ON notificacoes (tipo, referencia_id);

CREATE TABLE notificacoes_leituras (
  notificacao_id INTEGER NOT NULL REFERENCES notificacoes (id) ON DELETE CASCADE,
  usuario_id INTEGER NOT NULL REFERENCES usuarios (id) ON DELETE CASCADE,
  lido_em TEXT NOT NULL DEFAULT agora(),
  PRIMARY KEY (notificacao_id, usuario_id)
);

-- @down
DROP TABLE notificacoes_leituras;
DROP TABLE notificacoes;
