// Teste de ponta a ponta no Chrome real: sobe servidor com banco temporário e percorre os fluxos.
const { chromium } = require('playwright-core');
const { spawn, execFileSync } = require('child_process');
const assert = require('assert');
const fs = require('fs');
const os = require('os');
const path = require('path');

const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'pastoral-e2e-'));
const SHOTS = process.env.SHOTS || path.join(tmp, 'telas');
fs.mkdirSync(SHOTS, { recursive: true });
const PORT = 3400 + Math.floor(Math.random() * 400);
const env = { ...process.env, PORT, PASTORAL_DB: path.join(tmp, 'e2e.db'), PASTORAL_UPLOADS: path.join(tmp, 'up'), ADMIN_SENHA: 'Pastoral2026', PASTORAL_LIMITE_TENTATIVAS: '1000' };
const URL = `http://127.0.0.1:${PORT}`;
const passos = [];
const ok = (m) => { passos.push(m); console.log('  ✔', m); };

(async () => {
  execFileSync('node', ['src/seed.js', '--demo'], { env, stdio: 'ignore' });
  const srv = spawn('node', ['src/server.js'], { env, stdio: 'ignore' });
  await new Promise((r) => setTimeout(r, 1500));
  const png = path.join(tmp, 'foto.png');
  fs.writeFileSync(png, Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg==', 'base64'));

  const browser = await chromium.launch({ executablePath: '/usr/bin/google-chrome', args: ['--no-sandbox'] });
  const ctx = await browser.newContext({ viewport: { width: 1280, height: 800 }, locale: 'pt-BR' });
  const page = await ctx.newPage();
  const errosConsole = [];
  page.on('pageerror', (e) => errosConsole.push(e.message));
  page.on('console', (m) => { if (m.type() === 'error' && !/401|403|400|409/.test(m.text())) errosConsole.push(m.text()); });
  page.on('response', (r) => { if (r.status() === 404) console.log('    404:', r.url()); });
  page.on('dialog', (d) => d.accept());
  const shot = (n) => page.screenshot({ path: path.join(SHOTS, `${n}.png`), fullPage: true });
  const toast = async (txt) => page.locator('#toast div', { hasText: txt }).first().waitFor({ timeout: 5000 });
  const nav = (id) => page.locator(`.menu nav a[data-rota="${id}"]`).click();

  try {
    console.log('Login');
    await page.goto(URL);
    await page.waitForSelector('#f');
    await page.waitForTimeout(2200);
    await shot('01-login');
    await page.setViewportSize({ width: 390, height: 844 });
    await page.waitForTimeout(600);
    assert.ok((await page.evaluate(() => document.documentElement.scrollWidth - window.innerWidth)) <= 1, 'login no celular com rolagem horizontal');
    await shot('01b-login-celular');
    await page.setViewportSize({ width: 1280, height: 800 });
    await page.fill('#email', 'maria@pastoral.local');
    await page.fill('#senha', 'errada123');
    await page.click('#f button[type=submit]');
    await page.waitForFunction(() => document.getElementById('erro')?.textContent.includes('incorretos'));
    ok('login com senha errada mostra erro');
    await page.fill('#senha', 'Pastoral2026');
    await page.click('#f button[type=submit]');
    await page.waitForSelector('.banner');
    assert.match(await page.locator('.banner h2').innerText(), /Que bom ter você aqui, Maria/);
    ok('login correto leva ao painel');
    await page.waitForTimeout(1200);
    await shot('02-painel');

    console.log('Membros');
    await nav('membros');
    await page.waitForSelector('.membro');
    assert.strictEqual(await page.locator('.membro').count(), 7); // 6 demo + Maria
    await page.click('#novo');
    await page.fill('#nome', 'joana   d arc DA silva');
    await page.fill('#tel', '123');
    await page.click('#fm button:has-text("Salvar")');
    await page.waitForFunction(() => document.getElementById('er')?.textContent.includes('Telefone inválido'));
    ok('telefone inválido é recusado no cadastro');
    await page.fill('#tel', '47988887777');
    await page.fill('#nasc', '1990-09-30');
    await page.check('#lgpd');
    await page.click('#fm button:has-text("Salvar")');
    await toast('Membro cadastrado');
    await page.waitForFunction(() => document.getElementById('lista-m').innerText.includes('(47) 98888-7777'));
    ok('membro cadastrado com telefone formatado');
    await page.fill('#q', 'joana');
    await page.waitForFunction(() => document.querySelectorAll('.membro').length === 1);
    ok('busca filtra a lista');
    await page.click('button[data-a="editar"]');
    await page.fill('#nome', 'Joana Silva Editada');
    await page.click('#fm button:has-text("Salvar")');
    await toast('Membro atualizado');
    await page.waitForFunction(() => document.getElementById('lista-m').innerText.includes('Joana Silva Editada'));
    ok('edição de membro');
    await page.fill('#q', '');
    await page.waitForFunction(() => document.querySelectorAll('.membro').length === 8);
    await shot('03-membros');

    console.log('Frequência');
    await nav('frequencia');
    await page.waitForSelector('.chamada-item');
    assert.strictEqual(await page.locator('.chamada-item').count(), 8);
    await page.fill('#d', '2026-09-28');
    await page.waitForSelector('#cont');
    await page.click('#todos');
    assert.match(await page.locator('#cont').innerText(), /8 de 8/);
    await page.locator('.chamada-item').first().locator('button.ausente').click();
    await page.locator('.chamada-item').nth(1).locator('button.justificado').click();
    await page.locator('.chamada-item').nth(1).locator('input.obs').fill('Viagem');
    await page.fill('#b', 'joana');
    assert.strictEqual(await page.locator('.chamada-item').count(), 1);
    await page.fill('#b', '');
    ok('marcar todos, ausente, justificado com observação e busca');
    await shot('04-chamada');
    await page.click('#salvar');
    await toast('Chamada salva');
    await page.reload();
    await page.waitForSelector('.chamada-item');
    await page.fill('#d', '2026-09-28');
    await page.waitForFunction(() => document.getElementById('cont')?.textContent.includes('8 de 8'));
    const aus = await page.locator('.chamada-item').first().locator('button.ausente').getAttribute('aria-pressed');
    assert.strictEqual(aus, 'true');
    assert.strictEqual(await page.locator('.chamada-item').nth(1).locator('input.obs').inputValue(), 'Viagem');
    ok('chamada salva persiste após recarregar a página');

    // duas chamadas a mais para o primeiro membro estourar o limite de 3 faltas
    for (const d of ['2026-09-21', '2026-09-14']) {
      await page.fill('#d', d);
      await page.waitForFunction((x) => document.getElementById('d')?.value === x && !!document.getElementById('todos'), d);
      await page.waitForSelector('#todos');
      await page.locator('.chamada-item').first().locator('button.ausente').click();
      await page.click('#salvar');
      await toast('Chamada salva');
    }
    await page.goto(`${URL}/#/frequencia/analise`);
    await page.waitForSelector('#lim');
    await page.waitForSelector('.card.alerta');
    assert.ok((await page.locator('.card.alerta .selo.alerta').count()) >= 1);
    ok('3 faltas acumuladas disparam o alerta na análise');
    await shot('05-analise');
    await page.fill('#l', '5');
    await page.click('#lim button');
    await toast('Limite salvo');
    await page.waitForFunction(() => !document.querySelector('.card.alerta'));
    ok('mudar o limite para 5 remove o alerta');
    await page.goto(`${URL}/#/frequencia/relatorios`);
    await page.waitForSelector('table tbody tr');
    const [dl] = await Promise.all([page.waitForEvent('download'), page.click('a:has-text("CSV")')]);
    const csv = fs.readFileSync(await dl.path(), 'utf8');
    assert.ok(csv.includes('"Nome";"Telefone"') && csv.includes('Joana Silva Editada'));
    ok('relatório por período exporta CSV');

    console.log('Avisos');
    await nav('avisos');
    await page.waitForSelector('#novo-aviso');
    assert.match(await page.locator('.card.vazio').textContent(), /Nenhum aviso publicado/);
    await page.click('#novo-aviso');
    await page.waitForSelector('#fa');
    assert.match(page.url(), /#\/avisos\/novo$/);
    await page.fill('#titulo', 'Novena de São Miguel');
    await page.fill('#texto', 'Comunidade São Miguel, 19h.');
    await page.selectOption('#categoria', 'evento');
    await page.fill('#data_evento', '2026-10-05');
    await page.setInputFiles('#arquivo', png);
    await page.check('#fixado');
    assert.match(await page.locator('#previa').textContent(), /Novena de São Miguel/);
    assert.ok(await page.locator('#previa .fixado').count(), 'prévia mostra o aviso fixado');
    await shot('06a-aviso-novo');
    await page.click('#salvar');
    await toast('Aviso publicado');
    await page.waitForSelector('.aviso-resumo');
    await page.waitForFunction(() => { const i = document.querySelector('.aviso-resumo img'); return i && i.complete && i.naturalWidth > 0; });
    assert.ok(await page.locator('.aviso-resumo.fixado').count());
    assert.match(await page.locator('.aviso-resumo p').textContent(), /Comunidade São Miguel/);
    ok('novo aviso criado em página própria, com prévia ao vivo; aparece como cartão resumido');
    await shot('06-avisos');

    // modal: abrir conta como leitura; a flag volta para "não lido" e de novo para "lido"
    assert.strictEqual(await page.locator('.aviso-resumo.nao-lido').count(), 1);
    await page.click('.aviso-resumo .abrir');
    await page.waitForSelector('.aviso-modal');
    assert.match(await page.locator('.aviso-modal .m-texto').textContent(), /Comunidade São Miguel/);
    await page.waitForFunction(() => document.getElementById('m-flag').getAttribute('aria-pressed') === 'true');
    await page.click('#m-flag');
    await page.waitForFunction(() => document.getElementById('m-flag').getAttribute('aria-pressed') === 'false');
    await page.click('#m-x');
    assert.strictEqual(await page.locator('.aviso-resumo.nao-lido').count(), 1);
    await page.click('.aviso-resumo [data-flag]');
    await page.waitForFunction(() => document.querySelectorAll('.aviso-resumo.nao-lido').length === 0);
    await page.click('[data-f="nao-lidos"]');
    await page.waitForSelector('.card.vazio');
    await page.click('[data-f="lidos"]');
    await page.waitForSelector('.aviso-resumo');
    await page.click('[data-f="todos"]');
    ok('modal do aviso; flag de lido/não lido no modal e no cartão; filtros Todos, Não lidos e Lidos');

    // edição em página própria
    await page.click('.aviso-resumo .abrir');
    await page.click('#m-editar');
    await page.waitForSelector('#fa');
    assert.match(page.url(), /#\/avisos\/\d+\/editar$/);
    await page.fill('#titulo', 'Novena de São Miguel (19h)');
    await page.click('#salvar');
    await toast('Aviso atualizado');
    await page.waitForSelector('.aviso-resumo h3:has-text("(19h)")');
    ok('edição de aviso');

    console.log('Galeria');
    const f1 = path.join(tmp, 'Benção da imagem.png');
    const f2 = path.join(tmp, 'Procissão.png');
    fs.copyFileSync(png, f1); fs.copyFileSync(png, f2);
    await nav('galeria');
    await page.waitForSelector('#novo-evento');
    assert.match(await page.locator('.card.vazio').textContent(), /Nenhum evento/);
    await page.click('#novo-evento');
    await page.fill('#et', 'Festa de Nossa Senhora Aparecida');
    await page.fill('#ed', '2026-10-12');
    await page.fill('#ex', 'Missa campal e quermesse.');
    await page.click('#fe button:has-text("Criar evento")');
    await page.waitForSelector('#add-fotos');
    assert.match(page.url(), /#\/galeria\/\d+/);
    ok('coordenação cria o evento e cai direto na página dele');
    await page.click('#add-fotos');
    await page.setInputFiles('#arq', [f1, f2]);
    await page.waitForFunction(() => document.querySelectorAll('.previa').length === 2);
    await page.fill('[data-t="1"]', 'Procissão luminosa');
    await shot('07d-galeria-envio');
    await page.click('#enviar');
    await toast('2 foto(s) adicionada(s)');
    await page.waitForFunction(() => document.querySelectorAll('.grade-fotos .foto').length === 2);
    await page.waitForFunction(() => [...document.querySelectorAll('.grade-fotos img')].every((i) => i.complete && i.naturalWidth > 0));
    const titulos = await page.locator('.grade-fotos .legenda').allTextContents();
    assert.deepStrictEqual(titulos, ['Benção da imagem', 'Procissão luminosa']);
    ok('envio de 2 fotos com pré-visualização e títulos (nome do arquivo ou o digitado)');
    await page.waitForTimeout(900);
    await shot('07e-galeria-evento');
    await page.locator('.foto').first().click();
    await page.waitForSelector('#lb-foto');
    assert.match(await page.locator('#lb-pos').textContent(), /1 de 2/);
    await page.click('#lb-prox');
    assert.match(await page.locator('#lb-pos').textContent(), /2 de 2/);
    assert.strictEqual(await page.locator('#lb-titulo').textContent(), 'Procissão luminosa');
    await page.keyboard.press('ArrowLeft');
    assert.match(await page.locator('#lb-pos').textContent(), /1 de 2/);
    const [dlFoto] = await Promise.all([page.waitForEvent('download'), page.click('#lb-baixar')]);
    assert.match(dlFoto.suggestedFilename(), /^bencao-da-imagem\.png$/);
    assert.ok(fs.statSync(await dlFoto.path()).size > 0);
    ok('lightbox navega entre fotos (botões e teclado) e baixa a foto com o título como nome');
    await page.click('#lb-prox');
    await page.click('#lb-capa');
    await toast('Capa do evento atualizada');
    await page.click('#lb-excluir');
    await toast('Foto excluída');
    await page.waitForFunction(() => document.querySelectorAll('.grade-fotos .foto').length === 1);
    ok('coordenação define a capa e exclui uma foto específica');
    await page.click('#add-fotos');
    await page.setInputFiles('#arq', [f2]);
    await page.waitForFunction(() => document.querySelectorAll('.previa').length === 1);
    await page.click('#enviar');
    await toast('1 foto(s) adicionada(s)');
    await page.waitForFunction(() => document.querySelectorAll('.grade-fotos .foto').length === 2);
    const [dlZip] = await Promise.all([page.waitForEvent('download'), page.click('#baixar-tudo')]);
    assert.match(dlZip.suggestedFilename(), /festa-de-nossa-senhora-aparecida\.zip$/);
    assert.ok(fs.statSync(await dlZip.path()).size > 100);
    await page.click('#edit-evento');
    await page.fill('#et', 'Festa de N. Sra. Aparecida 2026');
    await page.click('#fe button:has-text("Salvar")');
    await toast('Evento atualizado');
    await page.waitForFunction(() => document.querySelector('.cabecalho-evento h2')?.textContent.includes('2026'));
    await page.click('.voltar');
    await page.waitForSelector('.evento-card');
    assert.match(await page.locator('.contador-fotos').textContent(), /2 fotos/);
    await page.waitForFunction(() => document.querySelector('.capa-evento img')?.complete);
    ok('baixar todas em .zip, editar o evento e ver o evento com a contagem de fotos na lista');
    await shot('07f-galeria-lista');

    console.log('Aniversariantes');
    await nav('aniversariantes');
    await page.waitForSelector('#fm');
    assert.ok((await page.locator('.membro').count()) >= 6);
    await page.fill('#msg', 'Parabéns, {nome}! Deus abençoe.');
    assert.match(await page.locator('#prev').innerText(), /Parabéns, Maria!/);
    await page.click('#fm button');
    await toast('Mensagem salva');
    await page.selectOption('#mes', '1');
    await page.waitForSelector('.vazio');
    ok('lista por mês, pré-visualização e salvar mensagem');
    await shot('07-aniversariantes');

    console.log('Financeiro');
    await nav('financeiro');
    await page.waitForSelector('.money');
    await page.click('#novo');
    await page.fill('#lv', 'abc');
    await page.fill('#ldesc', 'Oferta da missa de domingo');
    await page.click('#fl button:has-text("Salvar")');
    await page.waitForFunction(() => document.getElementById('er')?.textContent.includes('Valor inválido'));
    ok('valor inválido é recusado no lançamento');
    await page.fill('#lv', '1.500,50');
    await page.selectOption('#lc', 'oferta');
    await page.click('#fl button:has-text("Salvar")');
    await toast('Lançamento registrado');
    await page.click('#novo');
    await page.locator('label:has(input[value=saida])').click();
    await page.fill('#lv', '320,25');
    await page.selectOption('#lc', 'compras');
    await page.fill('#ldesc', 'Velas e flores');
    await page.click('#fl button:has-text("Salvar")');
    await toast('Lançamento registrado');
    await page.waitForFunction(() => document.querySelectorAll('tbody tr').length === 2);
    await page.waitForTimeout(1300);
    const valorEm = (n, re) => page.waitForFunction(([i, src]) => new RegExp(src).test((document.querySelectorAll('.money')[i]?.textContent || '').replace(/\s/g, ' ')), [n, re.source], { timeout: 8000 });
    await valorEm(0, /1\.500,50/);
    await valorEm(1, /320,25/);
    await valorEm(2, /1\.180,25/);
    ok('entrada e saída lançadas; entradas, saídas e saldo conferem (R$ 1.500,50 − 320,25 = 1.180,25)');
    await shot('07b-financeiro');
    await page.selectOption('#ft', 'saida');
    await page.waitForFunction(() => document.querySelectorAll('tbody tr').length === 1);
    await page.selectOption('#ft', '');
    await page.waitForFunction(() => document.querySelectorAll('tbody tr').length === 2);
    ok('filtro por tipo');
    await page.locator('button[data-a="editar"]').last().click(); // a entrada (mais antiga)
    await page.fill('#lv', '400,00');
    await page.click('#fl button:has-text("Salvar")');
    await toast('Lançamento atualizado');
    await valorEm(2, /79,75/); // 400,00 − 320,25
    ok('edição de lançamento recalcula o saldo');
    await page.locator('button[data-a="excluir"]').first().click(); // a saída
    await toast('Lançamento excluído');
    await page.waitForFunction(() => document.querySelectorAll('tbody tr').length === 1);
    await page.click('#ant');
    await page.waitForFunction(() => document.querySelector('.vazio'));
    await page.click('#prox');
    await page.waitForSelector('tbody tr');
    const [dl2] = await Promise.all([page.waitForEvent('download'), page.click('a:has-text("CSV")')]);
    assert.ok(fs.readFileSync(await dl2.path(), 'utf8').includes('Oferta da missa de domingo'));
    ok('exclusão, navegação entre meses e CSV do financeiro');

    console.log('Configurações');
    await nav('configuracoes');
    await page.waitForSelector('#fp');
    await page.setInputFiles('#foto', png);
    await toast('Foto atualizada');
    await page.waitForSelector('.topo img.avatar');
    ok('troca de foto reflete no topo');
    await page.fill('#tel', '47911112222');
    await page.fill('#nasc', '1985-04-12');
    await page.click('#fp button');
    await toast('Dados atualizados');
    await page.fill('#sa', 'Pastoral2026');
    await page.fill('#ns', 'NovaSenha2026');
    await page.fill('#cs', 'diferente');
    await page.click('#fs button');
    await page.waitForFunction(() => document.getElementById('e2').textContent.includes('confirmação'));
    await page.fill('#cs', 'NovaSenha2026');
    await page.click('#fs button');
    await toast('Senha alterada');
    ok('perfil salvo e senha exige confirmação');
    await shot('08-config');

    console.log('Sessão');
    await page.click('#sair');
    await page.waitForSelector('#f');
    await page.fill('#email', 'maria@pastoral.local');
    await page.fill('#senha', 'Pastoral2026');
    await page.click('#f button[type=submit]');
    await page.waitForFunction(() => document.getElementById('erro')?.textContent.includes('incorretos'));
    await page.fill('#senha', 'NovaSenha2026');
    await page.click('#f button[type=submit]');
    await page.waitForSelector('.banner');
    ok('logout e login com a nova senha (a antiga não vale mais)');

    console.log('Permissões (membro)');
    await page.goto(`${URL}/#/membros`);
    // cria login de membro pela coordenação e entra com ele
    await page.waitForSelector('.membro');
    await page.fill('#q', 'joana');
    await page.waitForFunction(() => document.querySelectorAll('.membro').length === 1);
    await page.click('button[data-a="editar"]');
    await page.fill('#mail', 'joana@teste.com');
    await page.fill('#pw', 'Joana12345');
    await page.click('#fm button:has-text("Salvar")');
    await toast('Membro atualizado');
    await page.click('#sair');
    await page.waitForSelector('#f');
    await page.fill('#email', 'joana@teste.com');
    await page.fill('#senha', 'Joana12345');
    await page.click('#f button[type=submit]');
    await page.waitForSelector('.banner');
    assert.strictEqual(await page.locator('.menu nav a').count(), 5);
    await page.waitForFunction(() => document.getElementById('badge-notif')?.textContent.trim() === '2'); // aviso novo + evento novo
    assert.strictEqual((await page.locator('#badge-notif').getAttribute('aria-hidden')), null);
    await nav('minha-presenca');
    await page.waitForSelector('.linha-tempo li');
    const hist = await page.locator('.linha-tempo').innerText();
    assert.ok(hist.includes('Viagem') && hist.includes('Justificada'), 'histórico da própria pessoa');
    assert.strictEqual(await page.locator('.linha-tempo li').count(), 1);
    await shot('07c-minha-presenca');
    await nav('galeria');
    await page.waitForSelector('.evento-card');
    assert.strictEqual(await page.locator('#novo-evento').count(), 0);
    await page.click('.evento-card');
    await page.waitForSelector('.grade-fotos .foto');
    for (const sel of ['#add-fotos', '#edit-evento', '#del-evento']) assert.strictEqual(await page.locator(sel).count(), 0, sel);
    await page.locator('.foto').first().click();
    await page.waitForSelector('#lb-foto');
    for (const sel of ['#lb-excluir', '#lb-titular', '#lb-capa']) assert.strictEqual(await page.locator(sel).count(), 0, sel);
    const [dlJoana] = await Promise.all([page.waitForEvent('download'), page.click('#lb-baixar')]);
    assert.ok(fs.statSync(await dlJoana.path()).size > 0);
    await page.keyboard.press('Escape');
    const [dlZipJ] = await Promise.all([page.waitForEvent('download'), page.click('#baixar-tudo')]);
    assert.ok(fs.statSync(await dlZipJ.path()).size > 100);
    await page.waitForFunction(() => document.getElementById('badge-notif').textContent.trim() === '1' && !document.getElementById('badge-notif').hidden); // só o aviso
    ok('usuário comum vê a galeria e baixa foto e .zip, sem nenhum botão de edição; abrir o evento tira a notificação dele do sino');
    assert.strictEqual((await page.evaluate(() => fetch('/api/financeiro').then((r) => r.status))), 403);
    await page.goto(`${URL}/#/membros`);
    await page.waitForSelector('.banner'); // redirecionada ao painel
    // sino: aviso e evento novos chegam como notificação
    await page.waitForFunction(() => document.getElementById('badge-notif') && !document.getElementById('badge-notif').hidden);
    assert.strictEqual((await page.locator('#badge-notif').textContent()).trim(), '1');
    assert.strictEqual(await page.locator('#badge-avisos').isVisible(), true);
    await page.click('#notif-btn');
    await page.waitForSelector('.notif-item');
    const itensSino = await page.locator('.notif-item strong').allTextContents();
    assert.ok(itensSino.some((t) => t.startsWith('Novo aviso: Novena')) && itensSino.some((t) => t.startsWith('Novo evento na galeria')), itensSino.join(' | '));
    await shot('07g-sino');
    await page.locator('.notif-item', { hasText: 'Novo aviso' }).click();
    await page.waitForSelector('.aviso-modal');
    assert.match(await page.locator('#m-titulo').textContent(), /Novena de São Miguel/);
    await page.waitForFunction(() => document.getElementById('badge-notif').hidden);
    await page.waitForFunction(() => document.getElementById('badge-avisos').hidden);
    for (const sel of ['#m-editar', '#m-excluir', '#m-leituras']) assert.strictEqual(await page.locator(sel).count(), 0, sel);
    await page.click('#m-x');
    assert.strictEqual(await page.locator('#novo-aviso').count(), 0);
    ok('usuário comum: sino avisa aviso e evento novos; clicar abre o aviso, tira do sino e zera o contador do menu; sem botões de gestão');
    ok('membro vê só 5 telas, sem formulário nem botões de gestão; rota de membros redireciona');
    await page.click('#sair');

    const entrar = async (email, senha) => {
      await page.waitForSelector('#f');
      await page.fill('#email', email);
      await page.fill('#senha', senha);
      await page.click('#f button[type=submit]');
      await page.waitForSelector('.banner');
    };
    const sair = async () => { await page.click('#sair'); await page.waitForSelector('#f'); };
    const linhaDe = (nome) => page.locator('table.perm tbody tr', { hasText: nome });

    console.log('Cadastro público');
    await page.waitForSelector('#f');
    await page.waitForSelector('#criar-conta:not([hidden])');
    await page.click('#criar-conta a');
    await page.waitForSelector('#confirma');
    await page.waitForTimeout(1600);
    await shot('01c-cadastro');
    await page.setViewportSize({ width: 390, height: 844 });
    await page.waitForTimeout(500);
    assert.ok((await page.evaluate(() => document.documentElement.scrollWidth - window.innerWidth)) <= 1, 'cadastro no celular com rolagem horizontal');
    await shot('01d-cadastro-celular');
    await page.setViewportSize({ width: 1280, height: 800 });
    await page.fill('#nome', 'paula  nova dos santos');
    await page.fill('#email', 'paula@teste.com');
    await page.fill('#tel', '47988881234');
    await page.fill('#senha', 'Paula12345');
    await page.fill('#confirma', 'Paula12345');
    await page.click('#f button[type=submit]');
    await page.waitForFunction(() => document.getElementById('erro')?.textContent.includes('LGPD'));
    await page.check('#lgpd');
    await page.fill('#confirma', 'outra12345');
    await page.click('#f button[type=submit]');
    await page.waitForFunction(() => document.getElementById('erro')?.textContent.includes('confirmação'));
    ok('cadastro exige consentimento LGPD e confirmação de senha');
    await page.fill('#confirma', 'Paula12345');
    await page.click('#f button[type=submit]');
    await page.waitForSelector('.banner');
    await toast('Conta criada');
    assert.match(await page.locator('.topo .secao').innerText(), /usuário/i);
    assert.deepStrictEqual(await page.locator('.menu nav a .l-longo').allInnerTexts(), ['Início', 'Minha presença', 'Avisos', 'Galeria', 'Configurações']);
    await page.goto(`${URL}/#/financeiro`);
    await page.waitForFunction(() => location.hash === '#/painel');
    await page.goto(`${URL}/#/aniversariantes`);
    await page.waitForFunction(() => location.hash === '#/painel');
    await page.goto(`${URL}/#/minha-presenca`);
    await page.waitForSelector('.anel');
    assert.match(await page.locator('.vazio').textContent(), /Nenhuma chamada/);
    ok('quem se cadastra entra como Usuário: só Início, Minha presença, Avisos, Galeria e Configurações (Financeiro e Aniversariantes redirecionam)');
    await sair();
    await page.click('#criar-conta a');
    await page.waitForSelector('#confirma');
    await page.fill('#nome', 'Outra Pessoa');
    await page.fill('#email', 'paula@teste.com');
    await page.fill('#senha', 'Paula12345');
    await page.fill('#confirma', 'Paula12345');
    await page.check('#lgpd');
    await page.click('#f button[type=submit]');
    await page.waitForFunction(() => document.getElementById('erro')?.textContent.includes('já está cadastrado'));
    ok('e-mail repetido é recusado');
    await page.click('.auth-link a');
    await page.waitForSelector('#olho');

    console.log('Usuários e acessos (administrador)');
    await entrar('admin@pastoral.local', 'Mestre2026');
    assert.strictEqual(await page.locator('.menu nav a').count(), 10);
    assert.match(await page.locator('.topo .secao').innerText(), /administrador/i);
    await page.goto(`${URL}/#/usuarios`);
    await page.waitForSelector('table.perm tbody .switch');
    assert.ok(await page.locator('table.perm tbody tr', { hasText: 'Administrador' }).count() >= 1);
    assert.ok(await linhaDe('admin@pastoral.local').locator('input[data-g="membros"]').isDisabled());
    await shot('08b-usuarios');
    await linhaDe('Joana Silva Editada').locator('input[data-g="frequencia"]').check();
    await toast('Frequência liberada para Joana');
    await linhaDe('Maria').locator('input[data-g="financeiro"]').uncheck();
    await toast('Financeiro bloqueada para Maria');
    assert.ok(await linhaDe('Joana Silva Editada').locator('.ponto-custom').count());
    ok('administrador vê todas as guias, é listado como Administrador (guias travadas) e libera/bloqueia guias por pessoa');
    await linhaDe('paula@teste.com').locator('select[data-cargo]').selectOption('coordenacao');
    await toast('Paula agora é Coordenação');
    await page.locator('#cad-aberto').uncheck();
    await toast('Cadastro fechado');
    ok('administrador promove a recém-cadastrada a Coordenação e fecha o cadastro');
    await sair();
    await page.waitForTimeout(600);
    assert.ok(await page.locator('#criar-conta').isHidden());
    await page.goto(`${URL}/#/cadastro`);
    await page.waitForFunction(() => document.getElementById('auth-card')?.innerText.includes('Cadastro fechado'));
    await page.goto(`${URL}/#/entrar`);
    ok('com o cadastro fechado o link some e a tela de cadastro avisa');

    await entrar('joana@teste.com', 'Joana12345');
    assert.strictEqual(await page.locator('.menu nav a').count(), 6);
    await page.goto(`${URL}/#/frequencia`);
    await page.waitForSelector('.chamada-item');
    assert.strictEqual(await page.evaluate(() => fetch('/api/financeiro').then((r) => r.status)), 403);
    assert.strictEqual(await page.evaluate(() => fetch('/api/membros').then((r) => r.status)), 403);
    await page.goto(`${URL}/#/configuracoes`);
    await page.waitForSelector('.cfg-grid');
    assert.strictEqual(await page.locator('.abas').count(), 0);
    ok('membro com a guia Frequência libertada entra na chamada, sem ganhar Financeiro nem Membros');
    await sair();

    await entrar('paula@teste.com', 'Paula12345');
    assert.strictEqual(await page.locator('.menu nav a').count(), 9);
    assert.strictEqual(await page.locator('.menu nav a[data-rota="usuarios"]').count(), 0);
    await page.goto(`${URL}/#/financeiro`);
    await page.waitForSelector('.money');
    ok('depois de promovida, Paula entra com as guias de Coordenação (9), sem a página Usuários');
    await sair();

    await entrar('maria@pastoral.local', 'NovaSenha2026');
    assert.strictEqual(await page.locator('.menu nav a').count(), 8);
    assert.strictEqual(await page.locator('.menu nav a[data-rota="financeiro"]').count(), 0);
    await page.goto(`${URL}/#/financeiro`);
    await page.waitForFunction(() => location.hash === '#/painel');
    assert.strictEqual(await page.evaluate(() => fetch('/api/usuarios').then((r) => r.status)), 403);
    assert.strictEqual(await page.evaluate(() => fetch('/api/financeiro').then((r) => r.status)), 403);
    ok('coordenação com Financeiro bloqueado perde a guia no menu, na rota e na API; não vê Permissões');
    await sair();

    await entrar('admin@pastoral.local', 'Mestre2026');
    await page.goto(`${URL}/#/usuarios`);
    await page.waitForSelector('table.perm tbody .switch');
    await page.locator('#cad-aberto').check();
    await toast('Cadastro aberto');
    await linhaDe('Maria').locator('button[data-restaurar]').click();
    await toast('Padrão restaurado para Maria');
    await linhaDe('Joana Silva Editada').locator('button[data-restaurar]').click();
    await toast('Padrão restaurado para Joana');
    assert.ok(await linhaDe('Maria').locator('input[data-g="financeiro"]').isChecked());
    ok('restaurar padrão devolve as guias da função');
    await sair();

    console.log('Responsivo');
    console.log('Sidebar recolhível e marca personalizável');
    await entrar('admin@pastoral.local', 'Mestre2026');
    assert.deepStrictEqual(await page.locator('.nav-titulo').allTextContents(), ['Geral', 'Gestão', 'Administração', 'Conta']);
    const larguraMenu = async () => (await page.locator('.menu').boundingBox()).width;
    assert.ok((await larguraMenu()) > 240);
    await page.click('#recolher');
    await page.waitForFunction(() => document.getElementById('shell').classList.contains('recolhido'));
    await page.waitForTimeout(700);
    assert.ok((await larguraMenu()) < 110, 'menu recolhido estreito');
    assert.strictEqual(await page.getAttribute('#recolher', 'aria-expanded'), 'false');
    assert.strictEqual(await page.locator('.menu nav a[data-rota="galeria"] .l-longo').evaluate((e) => getComputedStyle(e).opacity), '0');
    await page.hover('.menu nav a[data-rota="galeria"]');
    await page.waitForFunction(() => { const t = document.getElementById('tip-menu'); return t && !t.hidden && t.textContent === 'Galeria'; });
    await shot('13-sidebar-recolhido');
    await page.reload();
    await page.waitForSelector('#shell.recolhido');
    await page.click('#recolher');
    await page.waitForFunction(() => !document.getElementById('shell').classList.contains('recolhido'));
    await page.waitForTimeout(700);
    assert.ok((await larguraMenu()) > 240);
    ok('sidebar moderno com grupos; recolhe para ícones com dica ao passar o mouse, lembra a escolha e expande de volta');

    await page.goto(`${URL}/#/configuracoes/aparencia`);
    await page.waitForSelector('#salvar-cores');
    const cor = () => page.evaluate(() => document.documentElement.style.getPropertyValue('--cor-p'));
    assert.strictEqual(await page.locator('#salvar-cores').isDisabled(), true);
    await page.click('.preset[data-tema="1"]');
    assert.strictEqual(await cor(), '#14532d');
    assert.strictEqual(await page.locator('#salvar-cores').isDisabled(), false);
    await page.waitForTimeout(400);
    await shot('14-aparencia-verde');
    await page.fill('#cp-hex', '#ffee99');
    assert.match(await page.locator('#cp-c').textContent(), /Clara demais/);
    assert.strictEqual(await page.locator('#salvar-cores').isDisabled(), true);
    await page.click('.preset[data-tema="1"]');
    await page.click('#salvar-cores');
    await toast('Cores salvas');
    await page.reload();
    await page.waitForSelector('.menu');
    assert.strictEqual(await cor(), '#14532d');
    assert.strictEqual((await page.evaluate(() => fetch('/api/marca').then((r) => r.json()))).cor_principal, '#14532d');
    ok('cores: tema ao vivo, contraste bloqueia cor clara demais, salvar vale após recarregar e fica público');

    await page.goto(`${URL}/#/configuracoes/aparencia`);
    await page.waitForSelector('#arq-logo');
    await page.setInputFiles('#arq-logo', png);
    await toast('Logotipo atualizado');
    await page.waitForFunction(() => { const i = document.querySelector('.menu .marca .logo img'); return i && i.complete && i.naturalWidth > 0; });
    await shot('15-logotipo');
    await sair();
    await page.waitForSelector('.hero-conteudo .logo img');
    assert.strictEqual(await page.evaluate(() => getComputedStyle(document.documentElement).getPropertyValue('--cor-p').trim()), '#14532d');
    ok('logotipo aparece no menu e na tela de login, já com a cor nova (mesmo sem sessão)');
    await entrar('admin@pastoral.local', 'Mestre2026');
    await page.goto(`${URL}/#/configuracoes/aparencia`);
    await page.waitForSelector('#restaurar');
    await page.click('#restaurar');
    await toast('Marca restaurada');
    await page.waitForFunction(() => !document.querySelector('.menu .marca .logo img'));
    assert.strictEqual(await cor(), '#1d3766');
    assert.strictEqual((await page.evaluate(() => fetch('/api/marca').then((r) => r.json()))).logo, null);
    ok('restaurar padrão devolve as cores e remove o logotipo');

    for (const [nome, w, h] of [['celular', 390, 844], ['tablet', 768, 1024]]) {
      await page.setViewportSize({ width: w, height: h });
      await page.goto(`${URL}/#/painel`); await page.waitForSelector('.menu');
      if (nome === 'celular') assert.ok(await page.locator('#recolher').isHidden(), 'botão de recolher some no celular');
      for (const rota of ['painel', 'frequencia', 'frequencia/relatorios', 'aniversariantes', 'avisos', 'minha-presenca', 'galeria', 'membros', 'financeiro', 'usuarios', 'configuracoes', 'cadastro']) {
        await page.goto(`${URL}/#/${rota}`);
        await page.waitForTimeout(900);
        const sobra = await page.evaluate(() => document.documentElement.scrollWidth - window.innerWidth);
        assert.ok(sobra <= 1, `${nome} ${rota}: rolagem horizontal de ${sobra}px`);
      }
      const nav = await page.locator('.menu').boundingBox();
      assert.ok(nome === 'tablet' ? nav.height <= 80 : nav.y + nav.height >= h - 1, 'menu inferior visível');
      await page.goto(`${URL}/#/painel`); await page.waitForTimeout(1200); await shot(`09-painel-${nome}`);
      await page.goto(`${URL}/#/frequencia`); await page.waitForSelector('.chamada-item'); await page.waitForTimeout(800); await shot(`10-chamada-${nome}`);
      await page.goto(`${URL}/#/configuracoes`); await page.waitForSelector('.cfg-grid'); await page.waitForTimeout(800); await shot(`11-config-${nome}`);
      await page.goto(`${URL}/#/usuarios`); await page.waitForSelector('table.perm .switch'); await page.waitForTimeout(800); await shot(`12-usuarios-${nome}`);
      ok(`${nome} (${w}px): sem rolagem horizontal em 12 telas e menu inferior visível`);
    }

    assert.deepStrictEqual(errosConsole, [], 'erros no console: ' + errosConsole.join(' | '));
    ok('nenhum erro de JavaScript no console');
    console.log(`\n${passos.length} verificações OK. Capturas em ${SHOTS}`);
  } catch (e) {
    await shot('FALHA').catch(() => {});
    console.error('\nFALHOU:', e.message, `\nCaptura: ${SHOTS}/FALHA.png`);
    process.exitCode = 1;
  } finally {
    await browser.close();
    srv.kill();
  }
})();
